image: gitpod/workspace-full

tasks:
  - init: |
      wget https://get.jenkins.io/war-stable/latest/jenkins.war
  - command: |
      java -jar jenkins.war

ports:
  - port: 8080
    onOpen: open-preview
    visibility: public
